### ISSUE TITLE
I love this! It would be amazing to be able to remove non-trailing whitespace as well

### ISSUE THREAD

**Issue by tinacious** [SublimeText/TrailingSpaces#29]
This is a very useful plugin! I would love to also be able to remove whitespace that is not trailing and doesn't follow my indentation style (tabs vs. spaces).

Sometimes when copying code into a file the indenting ends up getting copied, e.g. if I use 4 spaces as tab size and use tabs instead of spaces for indentation.

``` css
.some-element {
    border: 1px solid #000; // my styles
      width: 200px; // copied styles
}
```

Note the extra whitespace yet it isn't trailing. Would it be possible for your plugin to remove the non-trailing whitespace as well and match my indentation style?

Thanks for your help!

![example](https://f.cloud.github.com/assets/1856992/124331/4965ebfa-6eea-11e2-88ee-ca7f23f629f6.png)
